FROM python:3.9-slim

# Set working directory
WORKDIR /logger

# Copy the logger script
COPY logger.py /logger/

# Create a log directory
RUN mkdir -p /logs && chmod 777 /logs

# Run log monitoring script
CMD ["python", "logger.py"]
